[package]
name = "sdanalysis"
version = "0.1.0"
authors = ["Malcolm Ramsay <malramsay64@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "gsd",
]

[dependencies]
gsd = {path="gsd", version="0.1.0"}
rstar = "0.5.1"
ndarray = "0.12.1"
nalgebra = "0.18.1"
structopt = {version="0.3.0", features=["paw"]}
paw = "1.0.0"
failure = "0.1.5"
streaming-stats = "0.2.2"
itertools="0.8.0"
serde = {version="~1.0.98", features=["derive"]}
csv = "1.1.1"
indicatif = "0.12.0"
