[package]
name = "gsd"
version = "0.1.0"
authors = ["Malcolm Ramsay <malramsay64@gmail.com>"]
edition = "2018"

[build-dependencies]
cc = "1.0"
bindgen = "0.42.2"

[dependencies]
ndarray = "0.12.1"
failure = "0.1.5"
